"use strict";

const { user, body_part } = require("../models");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          email: "1@1",
          name: "John Doe",
          password:
            "89025ee7a79cb494d63e23785ebcc161a4414bcc4b1191dcd88f43dab5086794bc91dad218c79fbb7b01f18725ca1d852bf87ba2673adef25b4a464d4ae96cb6",
          birth: "20000314",
          sex: "male",
          promise: "전지현이 될꺼야",
          profile: "https://i.ibb.co/wMjpgvr/profile.jpg",
          type: "normal",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: "123",
          name: "나는 관리자",
          password:
            "89025ee7a79cb494d63e23785ebcc161a4414bcc4b1191dcd88f43dab5086794bc91dad218c79fbb7b01f18725ca1d852bf87ba2673adef25b4a464d4ae96cb6",
          birth: "20000314",
          sex: "male",
          promise: "나는 관리자다!",
          profile: "https://i.ibb.co/wMjpgvr/profile.jpg",
          type: "normal",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
    // 방금 만든 유저의 아이디값 가져오기
    const newuser = await user.findOne({
      where: {
        email: "1@1",
      },
    });

    await queryInterface.bulkInsert(
      "body_part",
      [
        {
          body_part: "body_fat",
          goal: 10,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "chest",
          goal: 100,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "hip",
          goal: 95,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "shoulder",
          goal: 45,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "thigh",
          goal: 70,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "waist",
          goal: 72,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "weight",
          goal: 75,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "head",
          goal: 55,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "arm",
          goal: 40,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "height",
          goal: 175,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          body_part: "neck",
          goal: 42,
          user_id: newuser.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
    // 방금 만든 body_part의 id 가져오기
    const body_fat = await body_part.findOne({
      where: {
        body_part: "body_fat",
        user_id: newuser.id,
      },
    });

    const chest = await body_part.findOne({
      where: {
        body_part: "chest",
        user_id: newuser.id,
      },
    });

    const hip = await body_part.findOne({
      where: {
        body_part: "hip",
        user_id: newuser.id,
      },
    });

    const shoulder = await body_part.findOne({
      where: {
        body_part: "shoulder",
        user_id: newuser.id,
      },
    });

    const thigh = await body_part.findOne({
      where: {
        body_part: "thigh",
        user_id: newuser.id,
      },
    });

    const waist = await body_part.findOne({
      where: {
        body_part: "waist",
        user_id: newuser.id,
      },
    });

    const weight = await body_part.findOne({
      where: {
        body_part: "weight",
        user_id: newuser.id,
      },
    });

    const head = await body_part.findOne({
      where: {
        body_part: "head",
        user_id: newuser.id,
      },
    });

    const arm = await body_part.findOne({
      where: {
        body_part: "arm",
        user_id: newuser.id,
      },
    });

    const height = await body_part.findOne({
      where: {
        body_part: "height",
        user_id: newuser.id,
      },
    });

    const neck = await body_part.findOne({
      where: {
        body_part: "neck",
        user_id: newuser.id,
      },
    });

    await queryInterface.bulkInsert(
      "body_data",
      [
        {
          value: 24.8,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 23.6,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 23.1,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 21.7,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 20.4,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 20,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 18.7,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 18.8,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 18,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 17.8,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 16.1,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 15.8,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: body_fat.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.7,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 82.4,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 83.9,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 85.9,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 86.7,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 86,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 88.4,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 87.5,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 89.2,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 89.3,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 89.1,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 90,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: chest.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 75.1,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 78.6,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 78.3,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.5,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 81.6,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 81.3,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 83.4,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 82.1,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 84.9,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 84,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 84.3,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 85.8,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: hip.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.2,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.4,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 41,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 41.1,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 42.3,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 42.2,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 42.6,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 43.1,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 43.3,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 43.9,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 43.6,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 43.6,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: shoulder.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 65.6,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 65.9,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 65.3,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 65.8,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 66.9,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 65.2,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 66.3,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 66.3,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 66.1,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 67.9,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 67.8,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 68.2,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: thigh.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72.9,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72.5,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 71.3,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 71.1,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 70.4,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 71.6,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72.1,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72.6,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 73.7,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 73.6,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 72.7,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: waist.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.5,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.4,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.5,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.4,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79.6,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 80.7,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79.2,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79.3,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79.2,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 79.7,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 78.3,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: weight.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.2,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.2,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.3,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.3,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.4,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.3,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.4,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.2,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.1,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.2,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.4,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 55.3,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: head.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 33.7,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 33.7,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 33.2,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 34.6,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 33.2,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 34,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 34.3,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 33.9,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 34.6,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 34.8,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 35.4,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 35.5,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: arm.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.7,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.7,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.9,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.8,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.9,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 174.9,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: height.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 38.5,
          schedule: "20201130",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 38.3,
          schedule: "20201201",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 38.7,
          schedule: "20201202",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 39.1,
          schedule: "20201203",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 39.9,
          schedule: "20201204",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.5,
          schedule: "20201205",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 39.1,
          schedule: "20201206",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 39.4,
          schedule: "20201207",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.3,
          schedule: "20201208",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.5,
          schedule: "20201209",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 39.8,
          schedule: "20201210",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          value: 40.6,
          schedule: "20201211",
          user_id: newuser.id,
          body_part_id: neck.id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("users", null, {});
    await queryInterface.bulkDelete("body_part", null, {});
    await queryInterface.bulkDelete("body_data", null, {});
  },
};
